# Generated by Django 4.0.5 on 2022-06-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assignedmember_image_project_stage_team_teammember_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='members',
            new_name='project_members',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='assigned_members',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='members',
            new_name='team_members',
        ),
    ]
