import { Priority } from "utils";

export default function handler(req, res) {
  res.status(200).json({
    tasks: [
      {
        id: 1,
        project: { id: 1, name: "Morrison" },
        stage: { name: "Review", color: "e63232" },
        priority: Priority.High,
        tags: "Tag1",
        end_date: "2022/06/03",
        description: "Make the backend",
        comment_number: 10,
      },
      {
        id: 2,
        project: { id: 1, name: "Morrison" },
        stage: { name: "In Progress", color: "f3722c" },
        priority: Priority.Medium,
        tags: "Tag2 Tag3",
        end_date: "2022/06/04",
        description: "Learn graphene, build the GraphQL API",
        comment_number: 3,
      },
      {
        id: 3,
        project: { id: 2, name: "Abbott" },
        stage: { name: "Backlog", color: "f8961e" },
        priority: Priority.Low,
        tags: "Tag3",
        end_date: "2022/06/10",
        description:
          "Make responsive layouts for every page and handle long text that keeps going on and on and on and on and on and on...",
        comment_number: 1,
      },
      {
        id: 4,
        project: { id: 1, name: "Morrison" },
        stage: { name: "Review", color: "FFC71F" }, // FFCC33 ffd043 FFC71F
        priority: Priority.High,
        tags: "Tag1",
        end_date: "2022/06/12",
        description: "Make the backend",
        comment_number: 10,
      },
      {
        id: 5,
        project: { id: 1, name: "Morrison" },
        stage: { name: "In Progress", color: "7fc96b" },
        priority: Priority.Medium,
        tags: "Tag2 Tag3",
        end_date: "2022/06/13",
        description: "Learn graphene, build the GraphQL API",
        comment_number: 3,
      },
      {
        id: 6,
        project: { id: 2, name: "Abbott" },
        stage: { name: "Backlog", color: "43aa8b" },
        priority: Priority.Low,
        tags: "Tag3",
        end_date: "2022/05/20",
        description:
          "Make responsive layouts for every page and handle long text that keeps going on and on and on and on and on and on...",
        comment_number: 1,
      },
      {
        id: 7,
        project: { id: 1, name: "Morrison" },
        stage: { name: "Review", color: "277da1" },
        priority: Priority.High,
        tags: "Tag1",
        end_date: "2022/06/03",
        description: "Make the backend",
        comment_number: 10,
      },
      {
        id: 8,
        project: { id: 1, name: "Morrison" },
        stage: { name: "In Progress", color: "3b498e" },
        priority: Priority.Medium,
        tags: "Tag2 Tag3",
        end_date: "2022/06/04",
        description: "Learn graphene, build the GraphQL API",
        comment_number: 3,
      },
      {
        id: 9,
        project: { id: 2, name: "Abbott" },
        stage: { name: "Backlog", color: "66418a" },
        priority: Priority.Low,
        tags: "Tag3",
        end_date: "2022/06/10",
        description:
          "Make responsive layouts for every page and handle long text that keeps going on and on and on and on and on and on...",
        comment_number: 1,
      },
      {
        id: 10,
        project: { id: 1, name: "Morrison" },
        stage: { name: "Review", color: "22f55e" },
        priority: Priority.High,
        tags: "Tag1",
        end_date: "2022/06/12",
        description: "Make the backend",
        comment_number: 10,
      },
      {
        id: 11,
        project: { id: 1, name: "Morrison" },
        stage: { name: "In Progress", color: "3bf2f6" },
        priority: Priority.Medium,
        tags: "Tag2 Tag3",
        end_date: "2022/06/13",
        description: "Learn graphene, build the GraphQL API",
        comment_number: 3,
      },
      {
        id: 12,
        project: { id: 2, name: "Abbott" },
        stage: { name: "Backlog", color: "ef44ee" },
        priority: Priority.Low,
        tags: "Tag3",
        end_date: "2022/05/20",
        description:
          "Make responsive layouts for every page and handle long text that keeps going on and on and on and on and on and on...",
        comment_number: 1,
      },
      {
        id: 13,
        project: { id: 1, name: "Morrison" },
        stage: { name: "Review", color: "22f55e" },
        priority: Priority.High,
        tags: "Tag1",
        end_date: "2022/06/03",
        description: "Make the backend",
        comment_number: 10,
      },
      {
        id: 14,
        project: { id: 1, name: "Morrison" },
        stage: { name: "In Progress", color: "3bf2f6" },
        priority: Priority.Medium,
        tags: "Tag2 Tag3",
        end_date: "2022/06/04",
        description: "Learn graphene, build the GraphQL API",
        comment_number: 3,
      },
      {
        id: 15,
        project: { id: 2, name: "Abbott" },
        stage: { name: "Backlog", color: "ef44ee" },
        priority: Priority.Low,
        tags: "Tag3",
        end_date: "2022/06/10",
        description:
          "Make responsive layouts for every page and handle long text that keeps going on and on and on and on and on and on...",
        comment_number: 1,
      },
      {
        id: 16,
        project: { id: 1, name: "Morrison" },
        stage: { name: "Review", color: "22f55e" },
        priority: Priority.High,
        tags: "Tag1",
        end_date: "2022/06/12",
        description: "Make the backend",
        comment_number: 10,
      },
      {
        id: 17,
        project: { id: 1, name: "Morrison" },
        stage: { name: "In Progress", color: "3bf2f6" },
        priority: Priority.Medium,
        tags: "Tag2 Tag3",
        end_date: "2022/06/13",
        description: "Learn graphene, build the GraphQL API",
        comment_number: 3,
      },
      {
        id: 18,
        project: { id: 2, name: "Abbott" },
        stage: { name: "Backlog", color: "ef44ee" },
        priority: Priority.Low,
        tags: "Tag3",
        end_date: "2022/05/20",
        description:
          "Make responsive layouts for every page and handle long text that keeps going on and on and on and on and on and on...",
        comment_number: 1,
      },
    ],
  });
}
